name: Validator

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install jq
        
    - name: Run Validator
      run: |
        logPath="/github/workspace/logs/gitlog/"
        issueID="${{ github.event.pull_request.number }}"
        projectID="your_project_id"
        mergeID="your_merge_id"
        refname="${{ github.ref }}"
        gitlogfile="your_gitlogfile"
        gitpath="$logPath"
        gitinfo="your_gitinfo"
        guid="your_guid"
        branch="${{ github.head_ref }}"
        currenttime="$(date +%Y-%m-%dT%H:%M:%S)"
        
        validatorResponse=$(curl -X POST http://172.27.8.66:4010/validator \
          -H "Content-Type: application/json" \
          -d "{\"issueID\":\"$issueID\",\"projectID\":\"$projectID\",\"mergeID\":\"$mergeID\",\"refname\":\"$refname\",\"gitlogfile\":\"$gitlogfile\",\"gitpath\":\"$gitpath\",\"gitinfo\":\"$gitinfo\",\"guid\":\"$guid\",\"branch\":\"$branch\",\"currenttime\":\"$currenttime\"}" \
          --silent --write-out "HTTPSTATUS:%{http_code}")

        echo $validatorResponse >>test.log
        validatorout=$(echo $validatorResponse | sed -e 's/HTTPSTATUS\:.*//g')
        validatorstatus=$(echo $validatorResponse | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
        echo "ovalidatorOut" $validatorout >>test.log
        echo "validatorStatus" $validatorstatus >>test.log
        status=$(echo $validatorout | jq -r "['status']")
        validationStatus=$(echo $validatorout | jq -r "['validationStatus']")
        echo $validationStatus >> test.log
        echo $status >> test.log

        if [[ ${status} == "failure" ]]; then
          echo "inside failure " >> test.log
          validMsg=$(echo $validatorout | jq -r "['validationMsg']")
          echo "GL-HOOK-ERR: Devops Error Message:"
          echo "GL-HOOK-ERR: $validMsg"
          echo "GL-HOOK-ERR:"
          exit 1
        fi

        failedIn=$(echo $validatorout | jq -r "['failedIn']")
        echo $failedIn >> test.log
        if [ "${failedIn}" == "objectvalidation" ]; then
          errorMsg=$(echo $validatorout | jq -r "['validationStatus']")
          validMsg=$(echo $validatorout | jq -r "['validationMsg']")
          echo "GL-HOOK-ERR: Devops Error Message:"
          echo "GL-HOOK-ERR: $errorMsg"
          echo "GL-HOOK-ERR: $validMsg"
          exit 1
        fi
